NUMPY

In [9]:
import numpy as np
np.__version__

'2.3.5'

In [10]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [11]:
type(my_list)

list

In [12]:
arr = np.array(my_list) # create a numpy array from the list
arr

array([0, 1, 2, 3, 4, 5])

In [13]:
type(arr)

numpy.ndarray

ARANGE

In [22]:
np.arange() # it will print the array of values from 0 to 9 because the default start value is 0 and the default step value is 1 and the end value is 10 but not include 10

TypeError: arange() requires stop to be specified.

In [23]:
np.arange(10)  #arange it will print the value within interval 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(10,15) # it will print the value from 10 to 15 but not include 15

array([10, 11, 12, 13, 14])

In [28]:
np.arange(10,20,5) # it will print the value from 10 to 20 but not include 20 and the step size is 5

array([10, 15])

In [ ]:
np.arange(10,20,5,2) # it will print the value from 10 to 20 but not include 20 and the step size is 5 and the data type is int16

TypeError: Cannot interpret '2' as a data type

In [ ]:
np.arange(10,20) # it will print the value from 10 to 20 but not include 20 and the step size is 1 and the data type is int64

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20, 10) # it will print the value from 20 to 10 but not include 10 and the step size is 1 and the data type is int64

array([], dtype=int64)

In [ ]:
np.arange(-20,10) # it will print the value from -20 to 10 but not include 10 and the step size is 1 and the data type is int64

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

ZEROS

In [29]:
np.zeros(5) # it will print the array of 5 zeros

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros(5, dtype=int) #hyperparameter tunning it will print the array of 5 zeros and the data type is int

array([0, 0, 0, 0, 0])

In [31]:
np.zeros([5,10], dtype = int) # it will print the array of 5 rows and 10 columns and the data type is int

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ONES

In [ ]:
np.ones(5) # it will print the array of 5 ones

array([1., 1., 1., 1., 1.])

In [32]:
np.ones([3,5], dtype = int) # it will print the array of 3 rows and 5 columns and the data type is int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

RANDOM.RAND()

In [33]:
np.random.rand()  # it will print the random value between 0 and 1 and the data type is float64

0.8919345595839991

In [34]:
np.random.rand(2) # it will print the array of 2 random values between 0 and 1 and the data type is float64

array([0.28991988, 0.9882245 ])

In [36]:
np.random.rand(5) # it will print the array of 5 random numbers between 0 and 1

array([0.00750465, 0.57684671, 0.15680492, 0.30967986, 0.77654463])

In [ ]:
np.random.rand(3,2)  

array([[0.91101235, 0.28664266],
       [0.98854435, 0.18228087],
       [0.27685434, 0.7468667 ]])

In [ ]:
np.random.rand(3,2,9) #

array([[[0.19746601, 0.47916434, 0.95424952, 0.67009676, 0.28186301,
         0.02262229, 0.94071043, 0.25631748, 0.87000031],
        [0.4757189 , 0.88890991, 0.18563558, 0.07913003, 0.27475191,
         0.9423445 , 0.66368   , 0.47861542, 0.75582121]],

       [[0.47213111, 0.77264246, 0.68319352, 0.66359467, 0.8264928 ,
         0.80331844, 0.27938433, 0.62032847, 0.73963593],
        [0.58382021, 0.46233419, 0.54387142, 0.50159657, 0.73735161,
         0.99229673, 0.12079676, 0.75341395, 0.88369844]],

       [[0.66098943, 0.4047918 , 0.04669298, 0.73286343, 0.07846667,
         0.52268227, 0.30076806, 0.716849  , 0.31447889],
        [0.41782444, 0.38998519, 0.59506125, 0.14333026, 0.30082544,
         0.22924003, 0.48239599, 0.98690187, 0.38094984]]])

RANDOM.RANDINT()

In [ ]:
np.random.randint(3) # it will print the random integer value between 0 and 3 but not include 3

0

In [54]:
np.random.randint(5,10) # it will print the random integer value between 5 and 10 but not include 10

6

In [57]:
np.random.randint(5,10,3) # it will print the array of 3 random integer values between 5 and 10 but not include 10

array([9, 6, 8], dtype=int32)

In [ ]:
otp = np.random.randint(5,10,4)
print(otp)

[8 7 5 8]


In [ ]:
arr2 = np.random.randint(10,40,(10,10)) # it will print the array of 10 rows and 10 columns of random integer values between 10 and 40 but not include 40
print(arr2)

[[17 10 28 35 11 36 14 38 39 30]
 [37 20 29 32 21 30 20 26 13 22]
 [36 13 14 33 37 13 21 29 17 14]
 [26 33 24 19 16 18 10 30 13 19]
 [30 28 23 37 25 33 15 20 12 37]
 [39 39 22 36 25 25 29 14 19 29]
 [30 39 23 35 24 35 24 21 29 17]
 [13 24 16 26 10 25 12 10 16 31]
 [25 18 21 12 15 17 18 15 39 15]
 [17 29 23 38 13 27 11 33 29 29]]


In [ ]:
arr2

array([[17, 10, 28, 35, 11, 36, 14, 38, 39, 30],
       [37, 20, 29, 32, 21, 30, 20, 26, 13, 22],
       [36, 13, 14, 33, 37, 13, 21, 29, 17, 14],
       [26, 33, 24, 19, 16, 18, 10, 30, 13, 19],
       [30, 28, 23, 37, 25, 33, 15, 20, 12, 37],
       [39, 39, 22, 36, 25, 25, 29, 14, 19, 29],
       [30, 39, 23, 35, 24, 35, 24, 21, 29, 17],
       [13, 24, 16, 26, 10, 25, 12, 10, 16, 31],
       [25, 18, 21, 12, 15, 17, 18, 15, 39, 15],
       [17, 29, 23, 38, 13, 27, 11, 33, 29, 29]], dtype=int32)

In [64]:
arr2.shape # it will print the shape of the array which is 10 rows and 10 columns

NameError: name 'arr2' is not defined

,INDEXING,SLICING IN ARRAY

In [67]:
arr0=np.random.randint(3,5,(3,3)) # it will print the array of 3 rows and 3 columns of random integer values between 3 and 4 but not include 4
print(arr0)

[[3 4 4]
 [3 4 3]
 [3 3 4]]


In [68]:
arr0[:]

array([[3, 4, 4],
       [3, 4, 3],
       [3, 3, 4]], dtype=int32)

In [69]:
len(arr0) # it will print the length of the array which is 3 because there are 3 rows in the array

3

In [ ]:
arr0[0]

array([3, 3, 4], dtype=int32)

In [ ]:
arr0[1]

array([4, 4, 3], dtype=int32)

In [ ]:
arr0[:,1] # column slicing it will print the second column of the array 

array([3, 4, 4], dtype=int32)

In [ ]:
arr0[:,2]# 2 column slicing it will print the third column of the array

array([4, 3, 3], dtype=int32)

In [ ]:
arr0

array([[3, 3, 4],
       [4, 4, 3],
       [4, 4, 3]], dtype=int32)

In [ ]:
v = arr0[0, 2] # 
print(v)

4


In [78]:
arr2 = np.random.randint(10, 40, (10, 10)) 
print(arr2)
# it will print the array of 10 rows and 10 columns of random integer values between 10 and 40 but not include 40

[[36 32 21 39 12 10 21 19 16 17]
 [26 39 36 13 35 31 18 24 39 13]
 [21 32 20 35 33 21 14 38 31 27]
 [14 19 26 32 11 22 24 39 28 29]
 [28 11 25 17 18 32 15 10 30 34]
 [37 20 26 38 13 38 30 32 24 31]
 [13 29 38 19 33 24 19 20 16 25]
 [18 33 35 37 23 38 15 36 15 24]
 [32 34 28 19 23 16 17 25 21 29]
 [34 14 11 22 29 12 15 32 21 25]]


In [79]:
arr2

array([[36, 32, 21, 39, 12, 10, 21, 19, 16, 17],
       [26, 39, 36, 13, 35, 31, 18, 24, 39, 13],
       [21, 32, 20, 35, 33, 21, 14, 38, 31, 27],
       [14, 19, 26, 32, 11, 22, 24, 39, 28, 29],
       [28, 11, 25, 17, 18, 32, 15, 10, 30, 34],
       [37, 20, 26, 38, 13, 38, 30, 32, 24, 31],
       [13, 29, 38, 19, 33, 24, 19, 20, 16, 25],
       [18, 33, 35, 37, 23, 38, 15, 36, 15, 24],
       [32, 34, 28, 19, 23, 16, 17, 25, 21, 29],
       [34, 14, 11, 22, 29, 12, 15, 32, 21, 25]], dtype=int32)

In [ ]:
arr2[-7]# reverse indexing it will print the value of the element in the second row and first column of the array because the index starts from 0 and -7 means the second row and 0 means the first column

array([26, 33, 24, 19, 16, 18, 10, 30, 13, 19], dtype=int32)

In [ ]:
arr2[:, -7] # reverse column slicing it will print the value of the element in the second column of the array because the index starts from 0 and -7 means the second column and the colon means all the rows

array([35, 32, 33, 19, 37, 36, 35, 26, 12, 38], dtype=int32)

In [ ]:
arr2[:,-3]

array([38, 26, 29, 30, 20, 14, 21, 10, 15, 33], dtype=int32)

In [80]:
arr2

array([[36, 32, 21, 39, 12, 10, 21, 19, 16, 17],
       [26, 39, 36, 13, 35, 31, 18, 24, 39, 13],
       [21, 32, 20, 35, 33, 21, 14, 38, 31, 27],
       [14, 19, 26, 32, 11, 22, 24, 39, 28, 29],
       [28, 11, 25, 17, 18, 32, 15, 10, 30, 34],
       [37, 20, 26, 38, 13, 38, 30, 32, 24, 31],
       [13, 29, 38, 19, 33, 24, 19, 20, 16, 25],
       [18, 33, 35, 37, 23, 38, 15, 36, 15, 24],
       [32, 34, 28, 19, 23, 16, 17, 25, 21, 29],
       [34, 14, 11, 22, 29, 12, 15, 32, 21, 25]], dtype=int32)

In [ ]:
#array[row_start:row_end , column_start:column_end]
arr2[3:5,2:6] # it will print the value of the element in the fourth row and third column to the sixth column of the array because the index starts from 0 and 3 means the fourth row and 2 means the third column and 6 means the sixth column but not include 6

array([[26, 32, 11, 22],
       [25, 17, 18, 32]], dtype=int32)

In [95]:
arrp = np.random.randint(3,5,(4,4))
print(arrp)


[[3 4 4 3]
 [3 4 3 4]
 [4 4 3 3]
 [4 3 3 3]]


In [97]:
arrp[1]

array([3, 4, 3, 4], dtype=int32)

In [98]:
arrp[1,2]

np.int32(3)

array[row_start:row_end]

In [100]:
arrp[2:3]

array([[4, 4, 3, 3]], dtype=int32)

In [106]:
arrp[0:3] #

array([[3, 4, 4, 3],
       [3, 4, 3, 4],
       [4, 4, 3, 3]], dtype=int32)

In [109]:
arrp[1,2]

np.int32(3)

In [110]:
arrp[:,2]

array([4, 3, 3, 3], dtype=int32)

In [107]:
arr2

array([[36, 32, 21, 39, 12, 10, 21, 19, 16, 17],
       [26, 39, 36, 13, 35, 31, 18, 24, 39, 13],
       [21, 32, 20, 35, 33, 21, 14, 38, 31, 27],
       [14, 19, 26, 32, 11, 22, 24, 39, 28, 29],
       [28, 11, 25, 17, 18, 32, 15, 10, 30, 34],
       [37, 20, 26, 38, 13, 38, 30, 32, 24, 31],
       [13, 29, 38, 19, 33, 24, 19, 20, 16, 25],
       [18, 33, 35, 37, 23, 38, 15, 36, 15, 24],
       [32, 34, 28, 19, 23, 16, 17, 25, 21, 29],
       [34, 14, 11, 22, 29, 12, 15, 32, 21, 25]], dtype=int32)

Reshaping

In [112]:
arrp

array([[3, 4, 4, 3],
       [3, 4, 3, 4],
       [4, 4, 3, 3],
       [4, 3, 3, 3]], dtype=int32)

In [120]:
re = np.arange(2,8)
print(re)

[2 3 4 5 6 7]


In [121]:
re.reshape(2,3) # it will reshape the array of 6 elements into 2 rows and 3 columns because the total number of elements is 6 and the new shape is 2 rows and 3 columns

array([[2, 3, 4],
       [5, 6, 7]])

In [122]:
re.reshape(3,2) # it will reshape the array of 6 elements into 3 rows and 2 columns because the total number of elements is 6 and the new shape is 3 rows and 2 columns

array([[2, 3],
       [4, 5],
       [6, 7]])

In [123]:
re.reshape(6,1)

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [125]:
re.reshape(1,6) # it will reshape the array of 6 elements into 1 row and 6 columns

array([[2, 3, 4, 5, 6, 7]])

Masking  OR Filter in matrix

In [151]:
arr2 

array([[36, 32, 21, 39, 12, 10, 21, 19, 16, 17],
       [26, 39, 36, 13, 35, 31, 18, 24, 39, 13],
       [21, 32, 20, 35, 33, 21, 14, 38, 31, 27],
       [14, 19, 26, 32, 11, 22, 24, 39, 28, 29],
       [28, 11, 25, 17, 18, 32, 15, 10, 30, 34],
       [37, 20, 26, 38, 13, 38, 30, 32, 24, 31],
       [13, 29, 38, 19, 33, 24, 19, 20, 16, 25],
       [18, 33, 35, 37, 23, 38, 15, 36, 15, 24],
       [32, 34, 28, 19, 23, 16, 17, 25, 21, 29],
       [34, 14, 11, 22, 29, 12, 15, 32, 21, 25]], dtype=int32)

In [ ]:
arr2[1,4] # 1 row and 4 column value of the array

np.int32(35)

In [ ]:
arr2[-5,6]# -5

np.int32(30)

In [129]:
arr2 > 30

array([[ True,  True, False,  True, False, False, False, False, False,
        False],
       [False,  True,  True, False,  True,  True, False, False,  True,
        False],
       [False,  True, False,  True,  True, False, False,  True,  True,
        False],
       [False, False, False,  True, False, False, False,  True, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
         True],
       [ True, False, False,  True, False,  True, False,  True, False,
         True],
       [False, False,  True, False,  True, False, False, False, False,
        False],
       [False,  True,  True,  True, False,  True, False,  True, False,
        False],
       [ True,  True, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False,  True, False,
        False]])

In [132]:
arr2[arr2> 30]

array([36, 32, 39, 39, 36, 35, 31, 39, 32, 35, 33, 38, 31, 32, 39, 32, 34,
       37, 38, 38, 32, 31, 38, 33, 33, 35, 37, 38, 36, 32, 34, 34, 32],
      dtype=int32)

In [133]:
arr2[arr2 == 20]

array([20, 20, 20], dtype=int32)

In [134]:
arr2[arr2 != 35]

array([36, 32, 21, 39, 12, 10, 21, 19, 16, 17, 26, 39, 36, 13, 31, 18, 24,
       39, 13, 21, 32, 20, 33, 21, 14, 38, 31, 27, 14, 19, 26, 32, 11, 22,
       24, 39, 28, 29, 28, 11, 25, 17, 18, 32, 15, 10, 30, 34, 37, 20, 26,
       38, 13, 38, 30, 32, 24, 31, 13, 29, 38, 19, 33, 24, 19, 20, 16, 25,
       18, 33, 37, 23, 38, 15, 36, 15, 24, 32, 34, 28, 19, 23, 16, 17, 25,
       21, 29, 34, 14, 11, 22, 29, 12, 15, 32, 21, 25], dtype=int32)

In [146]:
np.max(arr2) # it will print the maximum value in the array

np.int32(39)

In [147]:
np.min(arr2) # it will print the minimum value in the array

np.int32(10)

In [148]:
np.sum(arr2) # it will print the sum of all the elements in the array

np.int64(2491)

In [149]:
arr2[-1,-2]

np.int32(21)